Problem Statement - Adjacency matrx representation of a graph

Pseudo Code : 

In [15]:
# Python Program

class Vertex:
    def __init__(self, id):
        self.id = id
        
    def getVertex(self):
        return self.id
    
    def setVertex(self, id):
        self.id = id
    
class Graph:
    def __init__(self, numVertices):
        self.numVertices = numVertices
        self.adjMat  = [[-1]*self.numVertices for i in range(self.numVertices)]
        self.vertices = []
        for x in range(self.numVertices):
            newVertex = Vertex(x)
            self.vertices.append(newVertex)
            
    def setVertex(self, vtx ,id):
        for x in range(self.numVertices):
            if(vtx == x):
                self.vertices[x].setVertex(id)
                
    def getVertex(self, id):
        for x in range(self.numVertices):
            if self.vertices[x].getVertex() == id:
                return x
                
    def addEdge(self, frm , to , count = 0):
#         Dirrected graph
        self.adjMat[self.getVertex(frm)][self.getVertex(to)] = count
#     In case of undirected graph
#         self.adjMat[self.getVertex(to)][self.getVertex(frm)] = count
            
    def viewMatrix(self):
        import numpy as np
        print np.matrix(self.adjMat)
            
            

In [16]:
G = Graph(5)
G.viewMatrix()

[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


In [17]:
G.setVertex(0 , 'a')
G.setVertex(1 , 'b')
G.setVertex(2 , 'c')
G.setVertex(3 , 'd')
G.setVertex(4 , 'e')
G.getVertex('a')

0

In [18]:
G.addEdge('a','b',1)

In [19]:
G.viewMatrix()

[[-1  1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


In [21]:
G.addEdge('b','d',1)
G.addEdge('b','e',1)

In [22]:
G.viewMatrix()

[[-1  1 -1 -1 -1]
 [-1 -1 -1  1  1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
